import os
# 🔥 CRITICAL: Hide the blocked GPU 0, expose empty GPUs 1, 2, and 3
os.environ["CUDA_VISIBLE_DEVICES"] = "1,2,3" 

import json
import torch
import chromadb
from sentence_transformers import SentenceTransformer
import os
from dotenv import load_dotenv
load_dotenv()

# --- CONFIGURATION ---
REGEX_JSON_DIR = "../../data/json"
RECURSIVE_JSON_DIR = "../../data/json_recursive"
CHROMA_PATH = "../../data/chroma_db"
COLLECTION_NAME = "legal_algeria"
MODEL_NAME = os.getenv("EMBEDDING_MODEL", "BAAI/bge-m3")

def process_regex_file(file_path, filename, collection, model, pool):
    """Processes JSONs generated by the Regex chunker using Multi-GPU."""
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if "documents" not in data:
        return 0

    ids, documents, metadatas = [], [], []
    total_chunks = 0

    for doc_idx, doc in enumerate(data["documents"]):
        parent_title = doc.get("title", "Sans titre")
        document_context = doc.get("context", parent_title)
        articles = doc.get("articles", [])
        
        # 🔥 C'EST ICI QUE LA VARIABLE DOIT ÊTRE DÉFINIE :
        page_numero = doc.get("page", "Inconnu")
        
        parent_id = f"{filename}_regex_doc_{doc_idx}"

        # Extract the Document Type from the title
        title_lower = parent_title.lower()
        if "décret" in title_lower: doc_type = "Décret"
        elif "arrêté" in title_lower: doc_type = "Arrêté"
        elif "décision" in title_lower: doc_type = "Décision"
        elif "loi" in title_lower: doc_type = "Loi"
        elif "ordonnance" in title_lower: doc_type = "Ordonnance"
        else: doc_type = "Autre"

        if not articles:
            # CAS 1 : AUCUN ARTICLE
            if document_context:
                ids.append(f"{parent_id}_full_context")
                documents.append(document_context)
                metadatas.append({
                    "source_file": filename,
                    "page": page_numero, # 👈 Utilisée ici
                    "document_type": doc_type,
                    "chunk_format": "full_context",
                    "chunking_method": "regex",
                    "parent_title": parent_title,
                    "parent_id": parent_id
                })
                total_chunks += 1
        else:
            # CAS 2 : IL Y A DES ARTICLES
            for art_idx, article_text in enumerate(articles):
                child_id = f"{parent_id}_art_{art_idx}"
                contextualized_text = f"Source: {parent_title}\nContenu: {article_text}"
                
                ids.append(child_id)
                documents.append(contextualized_text) 
                metadatas.append({
                    "source_file": filename,
                    "page": page_numero, # 👈 Utilisée ici
                    "document_type": doc_type,
                    "chunk_format": "article",
                    "chunking_method": "regex",
                    "parent_title": parent_title,
                    "parent_id": parent_id
                })
                total_chunks += 1

    if documents:
        # 🔥 MULTI-GPU ENCODING
        embeddings_array = model.encode(
            documents, 
            pool=pool, 
            batch_size=16
        )
        collection.add(
            ids=ids,
            documents=documents,
            embeddings=embeddings_array.tolist(),
            metadatas=metadatas
        )
    return total_chunks

def process_recursive_file(file_path, filename, collection, model, pool):
    """Processes JSONs generated by the Recursive chunker using Multi-GPU."""
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if "chunks" not in data:
        return 0

    ids, documents, metadatas = [], [], []
    total_chunks = 0

    for chunk in data["chunks"]:
        chunk_idx = chunk["chunk_index"]
        text = chunk["text"]
        
        # 🔥 Extraction sécurisée depuis le metadata du chunk
        metadata_dict = chunk.get("metadata", {})
        page_numero = metadata_dict.get("page", "Inconnu")

        ids.append(f"{filename}_recursive_chunk_{chunk_idx}")
        documents.append(text)
        
        metadatas.append({
            "source_file": filename,
            "page": page_numero, # 👈 Utilisée ici
            "chunking_method": "recursive",
            "chunk_index": chunk_idx,
            "chunk_format": "raw_text"
        })
        total_chunks += 1

    if documents:
        # 🔥 MULTI-GPU ENCODING
        embeddings_array = model.encode(
            documents, 
            pool=pool, 
            batch_size=1 
        )
        collection.add(
            ids=ids,
            documents=documents,
            embeddings=embeddings_array.tolist(),
            metadatas=metadatas
        )
    return total_chunks


def main():
    print(f"🔄 Initializing ChromaDB at: {CHROMA_PATH}...")
    client = chromadb.PersistentClient(path=CHROMA_PATH)
    
    try:
        client.delete_collection(COLLECTION_NAME)
        print("🗑️  Old collection deleted (Starting fresh).")
    except:
        pass
    
    collection = client.get_or_create_collection(name=COLLECTION_NAME)

    # 🔥 MEMORY OPTIMIZATIONS: FP16 and Flash Attention (sdpa) for 8K context
    print(f"🤖 Loading Model: {MODEL_NAME} in FP16 with Max Context...")
    model = SentenceTransformer(
        MODEL_NAME, 
        model_kwargs={
            "torch_dtype": torch.float16,
            "attn_implementation": "sdpa" 
        }
    )
    # Unlock the full context window!
    model.max_seq_length = 8192 

    # Start the worker pool for GPUs 1, 2, and 3
    print("🚀 Spawning Multi-GPU Worker Pool on 3 available GPUs...")
    pool = model.start_multi_process_pool()

    global_total_chunks = 0

    # --- 1. PROCESS REGEX JSONS ---
    print("\n--- Processing Regex Chunks ---")
    if os.path.exists(REGEX_JSON_DIR):
        regex_files = [f for f in os.listdir(REGEX_JSON_DIR) if f.endswith(".json")]
        for filename in regex_files:
            print(f"   📄 Processing {filename}...")
            global_total_chunks += process_regex_file(
                os.path.join(REGEX_JSON_DIR, filename), filename, collection, model, pool
            )
    else:
        print(f"⚠️ Regex directory not found: {REGEX_JSON_DIR}")

    # --- 2. PROCESS RECURSIVE JSONS ---
    print("\n--- Processing Recursive Chunks ---")
    if os.path.exists(RECURSIVE_JSON_DIR):
        recursive_files = [f for f in os.listdir(RECURSIVE_JSON_DIR) if f.endswith(".json")]
        for filename in recursive_files:
            print(f"   📄 Processing {filename}...")
            global_total_chunks += process_recursive_file(
                os.path.join(RECURSIVE_JSON_DIR, filename), filename, collection, model, pool
            )
    else:
        print(f"⚠️ Recursive directory not found: {RECURSIVE_JSON_DIR}")

    print("\n" + "="*60)
    print(f"🎉 INDEXING COMPLETE! Total Vectors: {global_total_chunks}")
    print("="*60)

    # 🔥 Always clean up the pool so we don't leave zombie processes behind
    model.stop_multi_process_pool(pool)
    print("🛑 Multi-GPU Pool successfully shut down.")

if __name__ == "__main__":
    main()