import os

# Helps reduce CUDA memory fragmentation on long embedding runs.
# Must be set before importing torch.
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

import json
import torch
import chromadb
from sentence_transformers import SentenceTransformer
from dotenv import load_dotenv

load_dotenv()

# --- CONFIGURATION ---
REGEX_JSON_DIR = "../../data/json"
RECURSIVE_JSON_DIR = "../../data/json_recursive"
TABLE_CHUNKS_JSON_DIR = "../../data/table_chunks"

CHROMA_PATH = "../../data/chroma_db"
COLLECTION_NAME = "legal_algeria"
MODEL_NAME = os.getenv("EMBEDDING_MODEL", "BAAI/bge-m3")

# Single-GPU local laptop settings.
# RTX 2070 Super Max-Q has limited VRAM, so keep these conservative.
ADD_BATCH_SIZE = 256
REGEX_ENCODE_BATCH_SIZE = 8
RECURSIVE_ENCODE_BATCH_SIZE = 2
TABLE_ENCODE_BATCH_SIZE = 16

# Optional safety: set REQUIRE_CUDA=1 to stop instead of silently using CPU.
REQUIRE_CUDA = os.getenv("REQUIRE_CUDA", "0") == "1"


def safe_metadata_value(value):
    """Chroma metadata must be str/int/float/bool and None-free."""
    if value is None:
        return ""
    if isinstance(value, (str, int, float, bool)):
        return value
    return json.dumps(value, ensure_ascii=False)


def clean_metadata(metadata):
    return {str(k): safe_metadata_value(v) for k, v in (metadata or {}).items()}


def add_encoded_batches(collection, model, ids, documents, metadatas, encode_batch_size, label):
    """Encode on a single GPU/CPU and add to Chroma in smaller batches."""
    if not documents:
        return 0

    total_added = 0
    for start in range(0, len(documents), ADD_BATCH_SIZE):
        end = start + ADD_BATCH_SIZE
        batch_ids = ids[start:end]
        batch_docs = documents[start:end]
        batch_metas = metadatas[start:end]

        embeddings_array = model.encode(
            batch_docs,
            batch_size=encode_batch_size,
            show_progress_bar=True,
        )

        collection.add(
            ids=batch_ids,
            documents=batch_docs,
            embeddings=embeddings_array.tolist(),
            metadatas=batch_metas,
        )

        total_added += len(batch_docs)
        print(f"      ➕ Added {total_added}/{len(documents)} {label} chunks")

        # Free unused CUDA cache between batches.
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    return total_added


def process_regex_file(file_path, filename, collection, model):
    """Processes JSONs generated by the regex chunker."""
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if "documents" not in data:
        return 0

    ids, documents, metadatas = [], [], []

    # Prefer the original TXT/PDF-ish source name inside the JSON when available.
    source_file = data.get("source_file", filename)

    for doc_idx, doc in enumerate(data["documents"]):
        parent_title = doc.get("title", "Sans titre")
        document_context = doc.get("context", parent_title)
        articles = doc.get("articles", [])
        page_numero = doc.get("page", "Inconnu")

        parent_id = f"{source_file}_regex_doc_{doc_idx}"

        title_lower = parent_title.lower()
        if "décret" in title_lower or "decret" in title_lower:
            doc_type = "Décret"
        elif "arrêté" in title_lower or "arrete" in title_lower:
            doc_type = "Arrêté"
        elif "décision" in title_lower or "decision" in title_lower:
            doc_type = "Décision"
        elif "loi" in title_lower:
            doc_type = "Loi"
        elif "ordonnance" in title_lower:
            doc_type = "Ordonnance"
        elif "convention" in title_lower:
            doc_type = "Convention"
        elif "accord" in title_lower:
            doc_type = "Accord"
        else:
            doc_type = "Autre"

        if not articles:
            if document_context:
                ids.append(f"{parent_id}_full_context")
                documents.append(document_context)
                metadatas.append(clean_metadata({
                    "source_file": source_file,
                    "page": page_numero,
                    "document_type": doc_type,
                    "chunk_format": "full_context",
                    "chunking_method": "regex",
                    "parent_title": parent_title,
                    "parent_id": parent_id,
                }))
        else:
            for art_idx, article_text in enumerate(articles):
                child_id = f"{parent_id}_art_{art_idx}"
                contextualized_text = f"Source: {parent_title}\nContenu: {article_text}"

                ids.append(child_id)
                documents.append(contextualized_text)
                metadatas.append(clean_metadata({
                    "source_file": source_file,
                    "page": page_numero,
                    "document_type": doc_type,
                    "chunk_format": "article",
                    "chunking_method": "regex",
                    "parent_title": parent_title,
                    "parent_id": parent_id,
                }))

    return add_encoded_batches(
        collection, model, ids, documents, metadatas,
        encode_batch_size=REGEX_ENCODE_BATCH_SIZE,
        label="regex",
    )


def process_recursive_file(file_path, filename, collection, model):
    """Processes JSONs generated by the recursive chunker."""
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if "chunks" not in data:
        return 0

    ids, documents, metadatas = [], [], []
    source_file = data.get("source_file", filename)

    for chunk in data["chunks"]:
        chunk_idx = chunk.get("chunk_index")
        text = chunk.get("text", "")
        if not text.strip():
            continue

        metadata_dict = chunk.get("metadata", {})
        page_numero = metadata_dict.get("page", "Inconnu")

        ids.append(f"{source_file}_recursive_chunk_{chunk_idx}")
        documents.append(text)
        metadatas.append(clean_metadata({
            "source_file": source_file,
            "page": page_numero,
            "chunking_method": "recursive",
            "chunk_index": chunk_idx,
            "chunk_format": "raw_text",
        }))

    return add_encoded_batches(
        collection, model, ids, documents, metadatas,
        encode_batch_size=RECURSIVE_ENCODE_BATCH_SIZE,
        label="recursive",
    )


def process_table_chunks_file(file_path, filename, collection, model):
    """Processes JSONs generated by the table side-car extractor."""
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if "chunks" not in data:
        return 0

    ids, documents, metadatas = [], [], []
    source_file = data.get("source_file", filename)

    for idx, chunk in enumerate(data["chunks"]):
        text = chunk.get("text", "")
        if not text.strip():
            continue

        chunk_id = chunk.get("id") or f"{source_file}_table_chunk_{idx + 1}"
        metadata_dict = chunk.get("metadata", {})

        # Keep the extractor metadata, but enforce standard fields.
        meta = dict(metadata_dict)
        meta.setdefault("source_file", source_file)
        meta.setdefault("page", metadata_dict.get("page", "Inconnu"))
        meta.setdefault("chunking_method", metadata_dict.get("chunking_method", "table_row"))
        meta.setdefault("chunk_format", metadata_dict.get("chunk_format", "table_row"))

        ids.append(str(chunk_id))
        documents.append(text)
        metadatas.append(clean_metadata(meta))

    return add_encoded_batches(
        collection, model, ids, documents, metadatas,
        encode_batch_size=TABLE_ENCODE_BATCH_SIZE,
        label="table",
    )


def process_directory(label, directory, processor, collection, model):
    total = 0
    print(f"\n--- Processing {label} Chunks ---")
    if not os.path.exists(directory):
        print(f"⚠️ {label} directory not found: {directory}")
        return 0

    json_files = [f for f in os.listdir(directory) if f.lower().endswith(".json")]
    if not json_files:
        print(f"⚠️ No JSON files found in: {directory}")
        return 0

    for filename in sorted(json_files):
        print(f"   📄 Processing {filename}...")
        total += processor(os.path.join(directory, filename), filename, collection, model)
    return total


def load_embedding_model():
    print("🔍 Torch CUDA check:")
    print(f"   torch.cuda.is_available(): {torch.cuda.is_available()}")
    print(f"   torch.version.cuda: {torch.version.cuda}")
    print(f"   torch.cuda.device_count(): {torch.cuda.device_count()}")

    if torch.cuda.is_available():
        print(f"   GPU: {torch.cuda.get_device_name(0)}")
        device = "cuda"
    else:
        if REQUIRE_CUDA:
            raise RuntimeError(
                "CUDA is not available, but REQUIRE_CUDA=1. "
                "Install a CUDA-enabled PyTorch build or unset REQUIRE_CUDA."
            )
        print("⚠️ CUDA not available. Falling back to CPU.")
        device = "cpu"

    print(f"🤖 Loading Model: {MODEL_NAME} on {device.upper()}...")

    model_kwargs = {}
    if device == "cuda":
        model_kwargs = {
            "torch_dtype": torch.float16,
            "attn_implementation": "sdpa",
        }

    try:
        model = SentenceTransformer(
            MODEL_NAME,
            device=device,
            model_kwargs=model_kwargs,
        )
    except TypeError:
        # Older sentence-transformers versions may not accept model_kwargs.
        print("⚠️ model_kwargs not supported by this SentenceTransformer version. Loading without them.")
        model = SentenceTransformer(MODEL_NAME, device=device)

    model.max_seq_length = 8192
    print(f"✅ Model loaded. Device: {device.upper()} | max_seq_length={model.max_seq_length}")
    return model


def main():
    print(f"🔄 Initializing ChromaDB at: {CHROMA_PATH}...")
    client = chromadb.PersistentClient(path=CHROMA_PATH)

    try:
        client.delete_collection(COLLECTION_NAME)
        print("🗑️  Old collection deleted (Starting fresh).")
    except Exception:
        pass

    collection = client.get_or_create_collection(name=COLLECTION_NAME)
    model = load_embedding_model()

    global_total_chunks = 0
    global_total_chunks += process_directory(
        "Regex", REGEX_JSON_DIR, process_regex_file, collection, model
    )
    global_total_chunks += process_directory(
        "Table", TABLE_CHUNKS_JSON_DIR, process_table_chunks_file, collection, model
    )
    global_total_chunks += process_directory(
        "Recursive", RECURSIVE_JSON_DIR, process_recursive_file, collection, model
    )

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    print("\n" + "=" * 60)
    print(f"🎉 INDEXING COMPLETE! Total Vectors: {global_total_chunks}")
    print("=" * 60)


if __name__ == "__main__":
    main()
